### ISSUE TITLE
Creating ServerQuery User

### ISSUE THREAD

**Issue by ghost** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#8]
How am I able to create a separate user for the serverquery. I have made the correct group with the YaTQA app but I am not sure how to make the serverquery user. If I try and use the serverquery login via the Tools menu in TeamSpeak, it just creates a query with the same permissions as I have.

**Comment by TerranUlm** [comment]
Sorry, somehow I missed that question. Create an new serverquery group and change the permissions like described in my description. Then add the new serverquery account to that group (and remove him from all other groups).

**Comment by ghost** [comment]
Thanks for your reply, I have managed to make a group for the plugin but if I try and connect to the server with the serverquery account I have made by Tools>ServerQuery Login and start removing server groups from it, it removes my real server groups as well.

**Comment by TerranUlm** [comment]
I don't get what you are actually doing. Are you editing the serverquery accounts server groups manually? Or are you editing the server groups of the server manually? Or is it about the behavior of the script? Later one is fully intentional, the script takes full control over the configured server groups, you cannot add users manually to those server groups as the will be removed automatically by the script. Everyone who should be in such a group needs to be added to the corresponding forum group (and he needs his TS ID added to his user profile).
